config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'services#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  resources :services, only: [:index, :show]
  resources :transactions, only: [:index]
  resources :offers do
    resources :transactions, except: [:destroy, :index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :service
  belongs_to :user
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :offers, class_name: "offer", foreign_key: "reference_id"
    has_one_attached :photo
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :offer
  belongs_to :user

  validates_presence_of :date, on: :create, message: "can't be blank"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

  def avatar
    return photo.key if photo.attached?
     
    "default_avatar"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :new

  def index
    @offers = policy_scope(Offer)
    @services = Service.all
    case params[:commit]
    when "Trouver mon prestataire"
      @textOffer = "Offres disponibles"
      if params[:query] == ""
        @offers = Offer.all
      else
        @offers = @offers.where(service_id: params[:query])
      end
    when "My offers"
      @textOffer = "Mes Offres"
      @offers = @offers.where(user_id: current_user)
      @transactions = Transaction.where(offer_id: @offers)
    end
  end

  def show
    @offer = Offer.find(params[:id])
    if params[:date]
      @date = Date.parse(params[:date])
    end
    authorize @offer
    @transaction = Transaction.new
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    authorize @offer
    if current_user
      @offer.user = current_user
      create_offer
    else
      redirect_to new_user_registration_path, notice: 'You are not logged in.'
    end
  end

  def edit
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def update
    @offer = Offer.find(params[:id])
    authorize @offer
    if @offer.update_attributes(offer_params)
      flash[:success] = "Object was successfully updated"
      redirect_to @offer
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    authorize @offer
    if @offer.destroy
      flash[:success] = 'Object was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to offers_path
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :price, :service_id)
  end

  def create_offer
    if @offer.save!
      flash[:success] = "Offer successfully created"
      redirect_to offer_path(@offer)
    else
      flash[:error] = "You are not connected !"
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    @services = policy_scope(Service)
  end

  def show
    @service = Service.find(params[:id])
    @services = Service.all
    authorize @service
    @offers = Offer.where(service_id: params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = policy_scope(Transaction)
    @transactions = @transactions.where(user_id: current_user)
  end

  def show
    @transaction = Transaction.find(params[:id])
    @transaction.transaction_price = @transaction.offer.price.to_i * @transaction.boat_size.to_i
    authorize @transaction
  end

  def new
    @offer = Offer.find(params[:offer_id])
    @transaction = Transaction.new
    authorize @transaction
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @transaction = Transaction.new(transaction_params)
    authorize @transaction
    if current_user
      @transaction.user = current_user
      @transaction.offer = @offer
      @transaction.statut = "pending"
      @transaction.transaction_price = @transaction.boat_size.to_i * @offer.price.to_i
      create_transaction
    else
      redirect_to offers_path, notice: 'You are not logged in.'
    end
  end

  def edit
    raise
  end

  def update
    @transaction = Transaction.find(params[:id])
    authorize @transaction
    case params[:commit]
    when "Annuler"
      @transaction.statut = "Cancelled"
    when "Refuser"
      @transaction.statut = "Refused"
    when "Accepter"
      @transaction.statut = "Confirmed"
    end
    update_transaction
  end

  private

  def transaction_params
    params.require(:transaction).permit(:boat_size, :transaction_price, :date)
  end

  def create_transaction
    if @transaction.save
      flash[:success] = "Transaction successfully created"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to transactions_path
  end

  def update_transaction
    if @transaction.update_attributes(statut: @transaction.statut)
      flash[:success] = "Object was successfully updated"
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
    redirect_to offers_path(commit: "My offers")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="main-container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/offers/edit.html.erb
<div class="container mt-4">
  <%= simple_form_for [@service, @offer] do |f| %>
    <%= f.input :title, label: 'Titre' %>
    <%= f.association :service, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
    <%= f.input :description %>
    <%= f.input :price, label: 'Prix au m2 (en €)' %>
    <%= f.button :submit, 'Ajouter mon offre', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/offers/index.html.erb
<div class="pl-4 pt-3"> <%= link_to "< Retour", :back, class: "back" %> </div>

  <div class="container mt-4">
    <% if params[:commit] != "My offers" %>
      <div class="container pb-4">
        <%= form_tag offers_path, class: 'form-inline home-search', method: :get do %>
          <%= select_tag 'query', options_from_collection_for_select(@services, 'id', 'title', params[:query]), prompt: 'Toutes nos offres', class: "form-control mr-2" %>
          <%= text_field_tag 'date', params[:date], class: "datepicker form-control mr-2" %>
          <%= submit_tag 'Trouver mon prestataire', class: "btn btn-primary" %>
        <% end %>
      </div>
    <% elsif params[:commit] == "My offers" %>

      <% if @transactions.count == 0 %>
      <% else %>
        <h1 class="mt-4">Demandes en attente</h1>

    <% end %>

    <div class="container cards">
      <% @transactions.each do |transaction| %>
        <% if transaction.statut == "pending" %>
          <div class="card-offer">
            <div class="border-bottom mb-2 p-2 d-flex justify-content-center">
              <%= link_to transaction.offer.title, offer_transaction_path(transaction.offer, transaction, date: params[:date]) %>
            </div>

            <div class="card-trip-infos d-flex flex-column align-items-center pl-3">
                <p><i class="fas fa-concierge-bell"></i> <%= Service.find(transaction.offer.service_id).title %></p>
                <p><i class="far fa-calendar-alt"></i> <%= transaction.date.strftime("%d-%m-%Y") %></p>
                <p><i class="fas fa-smile-wink"></i> <%= User.find(transaction.user_id).first_name %> <%= User.find(transaction.user_id).last_name %></p>
                 <p><i class="fas fa-ship"></i> <%= transaction.boat_size %> m²</p>
                <p><i class="fas fa-money-bill"></i> <%= transaction.transaction_price %> €</p>
                <%= simple_form_for [transaction.offer, transaction] do |f| %>
                  <%= f.button :submit, 'Accepter', class: 'btn btn-success' %>
                  <%= f.button :submit, 'Refuser', class: 'btn btn-danger' %>
                <% end %>
            </div>

          </div>
        <%end%>
      <% end %>
    </div>

    <% if @transactions.count == 0 %>
    <% else %>
      <h1 class="mt-4">Demandes acceptées</h1>
    <% end %>

      <div class="container cards">
        <% @transactions.each do |transaction| %>
          <% if transaction.statut == "Confirmed" %>
            <div class="card-offer">
              <div class="border-bottom mb-2 p-2 d-flex justify-content-center"><%= link_to transaction.offer.title, offer_transaction_path(transaction.offer, transaction) %></div>
                <div class="card-trip-infos d-flex flex-column align-items-center pl-3">
                  <p><i class="fas fa-concierge-bell"></i> <%= Service.find(transaction.offer.service_id).title %></p>
                  <p><i class="far fa-calendar-alt"></i> <%= transaction.date.strftime("%d-%m-%Y") %></p>
                  <p><i class="fas fa-smile-wink"></i> <%= User.find(transaction.user_id).first_name %> <%= User.find(transaction.user_id).last_name %></p>
                  <p><i class="fas fa-ship"></i> <%= transaction.boat_size %> m²</p>
                  <p><i class="fas fa-money-bill"></i> <%= transaction.transaction_price %> €</p>
                  <p><strong>Acceptée</strong></p>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class="row">


      <div class="container">
          <% if @offers.count == 0 %>
            <h1 class="mt-4"><%= @textOffer %></h1>
            <p>Vous n'avez publié aucune offre. <%= link_to "Publier ma première offre >", new_offer_path %> </p>
          <% else %>
          <h1 class="mt-4"><%= @textOffer %></h1>
          <div class="container cards">
            <% @offers.each do |offer| %>
              <%= link_to offer_path(offer, date: params[:date]) do %>
                  <div class="card-offer">
                    <div class="text-center mb-4">
                        <%= cl_image_tag offer.user.avatar, class: "avatar-large", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                        <h5 class="pt-4"><%= offer.user.first_name %> <%= offer.user.last_name %></h5>
                        <p class=""><%= offer.title %></p>
                      </div>
                      <div class="d-flex justify-content-end align-items-baseline">
                        <h4 class="mb-0"><%= offer.price %>€</h4>
                        <p class="mb-0 metre">/m²</p>
                      </div>
                  </div>
              <% end %>

            <% end %>
          </div>
          <% end %>

      </div>
    </div>
  </div>

app/views/offers/new.html.erb
<div class="pl-4 pt-3"> <%= link_to "< Retour", :back, class: "back" %> </div>


<div class="container mt-4 col-6">
	<h1>Proposer mes services</h1>
	<%= simple_form_for [@service, @offer] do |f| %>
	  <%= f.input :title, label: 'Titre' %>
	  <%= f.association :service, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
	  <%= f.input :description %>
	  <%= f.input :price, label: 'Prix au m2 (en €)' %>
	  <%= f.button :submit, 'Ajouter mon offre', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/offers/show.html.erb
<div class="pl-2 pt-3"><%= link_to "< Back", offers_path, class: "back"  %></div>
<div class="container">
  <div class="container">
    <div class="row">


      <div class="col-8 px-5 py-4">
        <div class="d-flex justify-content-between border-bottom align-items-center mb-4">
          <h2><%= @offer.title %></h2>
          <h2><%= @offer.price %> €</h2>
        </div>
        <div class="d-flex justify-content-between">
          <div class="align-self-center pr-5">
            <h2><%= @offer.user.first_name %> <%= @offer.user.last_name %></h2>
            <p><%= @offer.description %></p>
          </div>
          <%= cl_image_tag @offer.user.avatar, class: "avatar-xtra-large", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        </div>
      </div>

        <% if user_signed_in? %>
          <% if @offer.user_id != current_user.id %>

            <div class="col-4 card-order">
              <div class="container mt-4">
                <%= simple_form_for [@offer, @transaction] do |f| %>
                  <%= f.input :date, label: 'Date', as: :date, html5: true, input_html: {value: @date} %>
                  <%= f.input :boat_size, label: 'Quel est la taille de votre bateau ? (en m²)' %>
                  <%= f.button :submit, 'Demander une prestation', class: 'btn btn-primary' %>
                <% end %>
              </div>
          </div>
          
          <% elsif @offer.user_id == current_user.id %>

            <div class="container mt-4">
              <%= link_to edit_offer_path(@offer) do %><button type="button" class="btn btn-warning">Modifier l'offre</button><% end %>
              <%= link_to offer_path(@offer), method: :delete do %><button type="button" class="btn btn-danger">Supprimer l'offre</button><% end %>
            </div>
          <% end %>
        <% else %>
          <h4 class="mt-4">Connectez-vous pour réserver un créneau !</h4>
        <% end %>


    </div>
  </div>


</div>

app/views/services/index.html.erb
<div class="banner mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('bateau.jpg') %>);
">
  <div class="d-flex flex-column justify-content-center home-form">
    <h1>Trouvez le <strong>prestataire</strong> dont vous avez <strong>besoin</strong> !</h1>
    <p>Grâce à Hook, la plaisance redevient plaisante.</p>


    <%= form_tag offers_path, class: 'form-inline home-search', method: :get do %>
      <%= select_tag 'query', options_for_select(Service.all.collect{|u| [u.title, u.id]}), class: "form-control mr-2" %>
      <%= text_field_tag 'date', Date.today, class: "datepicker form-control mr-2" %>
      <%= submit_tag 'Trouver mon prestataire', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="container mb-2">
   <h2 class="my-4">Nos Services</h2>
  <div class="cards">
    <% @services.each do |service| %>
      <%= link_to service_path(service) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path service.photo.key, crop: :fill %>')">
            <h3> <%= service.title %></h3>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/services/show.html.erb
<div class="banner-show mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @service.photo.key %>');
">
  <div class="d-flex flex-column justify-content-center home-form">
    <h1><%= @service.title %></h1>
    <p><%= @service.description %></p>
    <%= form_tag offers_path, class: 'form-inline home-search', method: :get do %>
      <%= select_tag 'query', options_from_collection_for_select(@services, 'id', 'title', params[:id]), class: "form-control mr-2" %>
      <%= text_field_tag 'date', Date.today.strftime("%d-%m-%Y"), class: "datepicker form-control mr-2" %>
      <%= submit_tag 'Trouver mon prestataire', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="container">
  <h2 class="my-4">Les offres à la une</h2>

  <div class="row">
    <div class="container cards mb-2">
      <% @offers.take(3).each do |offer| %>
        <%= link_to offer_path(offer) do %>
            <div class="card-offer">
              <div class="text-center mb-4">
                  <%= cl_image_tag offer.user.avatar, class: "avatar-large", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <h5 class="pt-4"><%= offer.user.first_name %> <%= offer.user.last_name %></h5>
                  <p class=""><%= offer.title %></p>
                </div>
                <div class="d-flex justify-content-end align-items-baseline">
                  <h4 class="mb-0"><%= offer.price %>€</h4>
                  <p class="mb-0 metre">/m²</p>
                </div>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class=" d-flex justify-content-end"> <%= link_to "Toutes les offres >", offers_path(query: @service, commit: "Trouver mon prestataire"), class: "offer_link btn border" %></div>
</div>

app/views/shared/_footer.html.erb
<div class="footer position-sticky sticky-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by the Hook team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon w-100 fixed-top">
  <div class="collapse navbar-collapse">
  <%= link_to "/", class: "navbar-brand" do %>
    <h2 class="mb-0 text-primary"><i class="fas fa-water"></i></i> HOOK</h2>
  <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Trouver mon prestataire", "/offers", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Devenir prestataire", "/offers/new", class: "nav-link" %>
      </li>

    </ul>
  </div>
  
  <div class="collapse navbar-collapse">
    <% if user_signed_in? %>
      <ul class="list-unstyled mb-0">
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="navbarDropdown">
            <%= link_to "Mes réservations", transactions_path, :class => 'dropdown-item' %>
            <%= link_to "Mes offres", offers_path(commit: "My offers"), :class => 'dropdown-item' %>
            <%= link_to 'Mon profil', edit_user_registration_path, :class => 'dropdown-item' %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="list-unstyled mb-0">
        <div class="d-flex">
          <li class="nav-item active">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link btn rounded" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link btn btn-primary" %>
          </li>
        </div>
      </ul>
    <% end %>
  </div>
</div>

app/views/transactions/edit.html.erb
<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<div class="pl-4 pt-3"> <%= link_to "< Retour", :back, class: "back" %> </div>

<div class="container py-4">
  <% if @transactions == [] %>
    <h1> Vous n'avez aucune réservations pour le moment</h1>
    <%= link_to "Demander une prestation", services_path, class: "btn btn-primary mt-3 flex-center"  %>
  <% else %>
    <h1 class="pb-4"> Mes Réservations</h1>
    <div class="cards">
      <% @transactions.each do |transaction| %>
          <% if transaction.boat_size %>
            <div class="card-offer">
              <div class="border-bottom mb-2 pb-3 d-flex justify-content-between align-items-center">
                <h6><strong><%= Offer.find(transaction.offer_id).title %></strong></h6>
                <%= cl_image_tag transaction.offer.user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              </div>

              <div class="card-trip-infos d-flex flex-column align-items-center pt-3">
                <p><i class="fas fa-ship"></i> <%= transaction.boat_size %>m2</p>
                <p><i class="far fa-calendar-alt"></i> <%= transaction.date.strftime("%d-%m-%Y") %></p>
                <p><i class="fas fa-money-bill"></i> <%= Offer.find(transaction.offer_id).price.to_i * transaction.boat_size.to_i  %> €</p>
                <% if transaction.statut =="Cancelled" %>
                  <p><strong>Annulée</strong></p>
                <% elsif transaction.statut == "Refused"%>
                  <p><strong>Refusée</strong></p>
                <% elsif transaction.statut == "Confirmed"%>
                  <p><strong>Confirmée</strong></p>
                <% end %>
                <% if transaction.user == current_user %>
                    <% if transaction.statut == "pending" %>
                      <%= simple_form_for [transaction.offer, transaction] do |f| %>
                        <%= f.button :submit, 'Annuler', class: 'btn btn-primary' %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/transactions/new.html.erb
<div class="container mt-4">
	<%= simple_form_for [@offer, @transaction] do |f| %>
	  <%= f.input :date, label: 'Date'%>
	  <%= f.input :boat_size, label: 'Quel est la taille de votre batiment ? (en m²)' %>
	  <%= f.button :submit, 'Demander une prestation', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/transactions/show.html.erb
<h1> Merci d'avoir choisi notre service de <%= @transaction.offer.service.title %> </h1>

<h3> Votre prestataire est <%= @transaction.user.first_name %> <%= @transaction.user.last_name %></h3>
<h3> Il viendra le <%= @transaction.date %> </h3>
<h3> Pour <%= @transaction.transaction_price %>€ </h3>

app/views/transactions/update.html.erb
<h1>Transactions#update</h1>
<p>Find me in app/views/transactions/update.html.erb</p>

app/views/users/index.html.erb
<h1> All users </h1>

<% @users.each do |user| %>
  <%= link_to user.email, user_path(user) %>
<% end %>

app/views/users/show.html.erb
<h1><%=  @user.email %></h1>